spring:
    profiles:
        active: prod
    datasource:
        url: jdbc:mysql://localhost:3306/springboot-db?useSSL=false
        username: root
        password: "!qaz2wsx"
        driver-class-name: com.mysql.cj.jdbc.Driver
        sql-script-encoding: UTF-8
        druid:
            initial-size: 5
            max-active: 20
            min-idle: 10
            max-wait: 10
            web-stat-filter:
                enable: true
                url-pattern: /*
                execlusions: "*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*"
            stat-view-servlet:
                enable: true
                url-pattern: /druid/*
                reset-enable: true
                login-username: admin
                login-password: admin
                allow:
                deny:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect
        hibernate:
            ddl-auto: update
    security:
        user:
            name: "a"
            password: "a"
mybatis-plus:
    global-config:
        db-config:
            db-type: mysql
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type: TRACE
myperson:
    name: Adam
    age: 34
    say: Hello world config

---

server:
    port: 4000
spring:
    profiles: prod
---

server:
    port: 4001
spring:
    profiles: dev

---

server:
    port: 4002
spring:
    profiles: test

---