
server:
    port: 4000
spring:
    datasource:

        url: jdbc:mysql://localhost:3306/springboot-db?useSSL=false

        username: root

        password: "!qaz2wsx"

        driver-class-name: com.mysql.cj.jdbc.Driver

        sql-script-encoding: UTF-8

    jpa:

        properties:

            hibernate:

                dialect: org.hibernate.dialect.MySQL57Dialect

        hibernate:

            ddl-auto: update


logging:

    level:

        org:

            hibernate:

                SQL: DEBUG

                type: TRACE